CREATE TABLE IF NOT EXISTS migrations(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT
    name VARCHAR(255) UNIQUE NOT NULL DEFAULT '',
    checksum VARCHAR(40) NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS artist(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    name VARCHAR(255) UNIQUE NOT NULL DEFAULT ''
);

CREATE TABLE IF NOT EXISTS album(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL DEFAULT '',
    artist BIGINT NOT NULL REFERENCES artist(id),
    published BOOLEAN NOT NULL DEFAULT FALSE,
    rating SMALLINT(5) NOT NULL DEFAULT 0
);

CREATE TABLE IF NOT EXISTS track(
    id BIGINT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    title VARCHAR(255) NOT NULL DEFAULT '',
    album BIGINT NOT NULL REFERENCES album(id),
    rating SMALLINT(5) NOT NULL DEFAULT 0
);
